on:
  workflow_dispatch:
    inputs:
      tool:
        description: 'Opendigitalradio tool'
        required: true
        default: 'odr-audioenc'
      codename:
        description: 'Debian codename'
        required: true
        default: 'sid'

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
        with:
          github-server-url: 'https://salsa.debian.org'
          repository: ralex/${{ inputs.tool }}
          ref: 'debian/latest'
          token: ${{ secrets.SALSA }}
      -
        name: build-deb-amd64
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: "debian:${{ inputs.codename }}-slim"
          buildpackage-opts: --build=binary
          host-arch: amd64
      -
        name: build-deb-arm64
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: "debian:${{ inputs.codename }}-slim"
          buildpackage-opts: --build=binary
          host-arch: arm64
      -
        name: build-deb-armhf
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: "debian:${{ inputs.codename }}-slim"
          buildpackage-opts: --build=binary
          host-arch: armhf
      -
        name: Upload packages to ODR debian repository
        uses: nicklasfrahm/scp-action@main
        with:
          direction: upload
          host: ${{ secrets.SSH_HOST }}
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            debian/artifacts/*.deb
            debian/artifacts/*.changes
          target: /home/robinalexander/incoming
      -
        name: upload
        uses: actions/upload-artifact@v3
        with:
          path: debian/artifacts/
          name: ${{ inputs.tool }}-${{ inputs.codename }}
