on:
  workflow_dispatch:

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
        with:
          github-server-url: 'https://salsa.debian.org'
          repository: 'ralex/odr-audioenc'
          ref: 'debian/latest'
      -
        name: build-deb-amd64
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
          host-arch: amd64
      -
        name: build-deb-arm64
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
          host-arch: arm64
      -
        name: build-deb-armhf
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
          host-arch: armhf
      -
        name: upload
        uses: actions/upload-artifact@v3
        with:
          path: debian/artifacts/
          name: odr-audioenc
