on:
  workflow_dispatch:
    inputs:
      tool:
        description: 'Opendigitalradio tool'
        required: true
        default: 'odr-audioenc'

jobs:
  build-debs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64, armhf]
        codename: [bullseye, bookworm]
    steps:
      -
        name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      -
        name: checkout
        uses: actions/checkout@v3
        with:
          github-server-url: 'https://salsa.debian.org'
          repository: ralex/${{ inputs.tool }}
          token: ${{ secrets.SALSA }}
          ref: debian/latest
          fetch-depth: '0'
      -
        name: build-deb
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: "debian:${{ matrix.codename }}-slim"
          buildpackage-opts: --build=full --force-sign
          extra-build-deps: git gpg pristine-tar
          before-build-hook: pristine-tar checkout ../$(pristine-tar list)
          host-arch: ${{ matrix.arch }}
      -
        name: rsync over ssh
        run: rsync -rv -e 'ssh -p 222' ./debian/artifacts/ robinalexander@mpb.li:incoming/${{ matrix.codename }}
