on:
  workflow_dispatch:
    inputs:
      tool:
        description: 'Opendigitalradio tool'
        required: true
        default: 'odr-audioenc'
      codename:
        description: 'Debian codename'
        required: true
        default: 'sid'

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
        with:
          github-server-url: 'https://salsa.debian.org'
          repository: ralex/${{ inputs.tool }}
          token: ${{ secrets.SALSA }}
          ref: debian/latest
          fetch-depth: '0'
      -
        name: build-deb-amd64
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: "debian:${{ inputs.codename }}-slim"
          buildpackage-opts: --build=full --force-sign
          extra-build-deps: git gpg pristine-tar
          before-build-hook: pristine-tar checkout ../$(pristine-tar list)
          host-arch: amd64
      -
        name: upload
        uses: actions/upload-artifact@v3
        with:
          path: debian/artifacts/
          name: ${{ inputs.tool }}-${{ inputs.codename }}
